import 'package:flutter/widgets.dart';
import 'package:magic/magic.dart';

import 'label_card.recipe.dart';

/// The label card size axis.
enum LabelCardSize {
  /// A small stock label, where only the name and the code fit.
  sm,

  /// The readable proof shown beside the sheet.
  md,
}

/// **LabelCard**
///
/// One label at a size a person can read: what will be printed on it, and what will not
/// fit.
///
/// **It exists because the sheet preview cannot show content.** An A4 in a half-screen
/// column puts 9pt text at about six pixels, so [LabelPreview] draws the shape of each
/// label and this shows one of them properly. That is the same split Word and Avery make,
/// and it is what keeps criterion 7 honest: neither view pretends to be the other.
///
/// **A field that does not fit is named, not truncated.** The doc is explicit about it, and
/// the reason is that truncation looks like a design choice in a preview and like a defect
/// on a printed sheet of 200. The overflow line carries the `expired` tone, which in this
/// palette is `destructive`, because a sheet printed wrong is a sheet thrown away.
@immutable
class LabelCard extends StatelessWidget {
  /// The product name, the label's first line.
  final String name;

  /// The second line: location, team name, or whatever the layout enabled.
  final String? meta;

  /// The barcode digits, printed under the bars so a damaged label can still be typed in.
  final String code;

  /// The already-localised name of the field that will not fit, when one will not.
  final String? overflowField;

  /// The card size.
  final LabelCardSize size;

  /// Creates a [LabelCard].
  const LabelCard({
    super.key,
    required this.name,
    required this.code,
    this.meta,
    this.overflowField,
    this.size = LabelCardSize.md,
  });

  @override
  Widget build(BuildContext context) {
    final slots = labelCardRecipe()(variants: {'size': size.name});

    return WDiv(
      className: slots['root'],
      children: [
        WDiv(
          className: slots['head'],
          children: [
            // No truncate: the overflow line below says the name does not fit, and a
            // preview that both warns and truncates hides what the warning is about.
            WText(name, className: slots['name']),
            if (meta != null) WText(meta!, className: slots['meta']),
          ],
        ),
        WDiv(
          className: slots['bars'],
          child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: _bars(slots)),
        ),
        WText(code, className: slots['code']),
        if (overflowField != null) WText('$overflowField sığmıyor', className: slots['overflow']),
      ],
    );
  }

  /// Bars derived from the digits, so the same code always draws the same pattern.
  ///
  /// Not a real symbology and not pretending to be: the printed sheet is generated by
  /// `pdf` plus `barcode_widget`, and this is the shape of the thing at review time.
  List<Widget> _bars(Map<String, String> slots) {
    final List<int> digits = code.codeUnits
        .where((c) => c >= 0x30 && c <= 0x39)
        .map((c) => c - 0x30)
        .toList();

    return <Widget>[
      for (final int digit in digits) ...<Widget>[
        Expanded(
          flex: 1 + digit % 3,
          child: WDiv(className: slots['bar']),
        ),
        Expanded(flex: 1 + (digit + 1) % 2, child: const SizedBox.shrink()),
      ],
    ];
  }
}
